### PR TITLE
Change user profile model

### PR DESCRIPTION
**Pull request by mojcas**
Model UserProfile changed to introduce more meaningful ACTIVITY_LEVEL_CHOICES values, and to avoid duplication of fields inherited from Django User model

### CODE REVIEW

**Comment by goranche** [comment]
given the amount of changes to the model, shouldn't there also be a migrations file? :thought_balloon:

**Comment by goranche** [comment]
also, why are you changing the permissions on manage.py?
please leave that file as it is, some of us actually "depend" on those permissions  (not life or death depend, but sane or go insane depend)

**Comment by mojcas** [comment]
Those permissions, I tried to get rid of those for a while but have given up for now (it's happening for some reason with (manage.py, static/css/jquery.datetimepicker.css,  static/js/jquery.datetimepicker.js)
 I am not sure how, as I am using Windows, and I can't make Git ignore these. Can you help?

**Comment by goranche** [comment]
leave the permissions be, I'll fix it when (if? :smiling_imp: ) we merge this PR

you should **always** check what will be included in a commit (git status) and remove the changes you do not want to happen... things like this can be avoided :wink:

**Comment by mojcas** [comment]
Okay, I was going back and forth a lot, to sync origin master with upstream, this has sneaked in somehow at some point. Thanks to fix it!

**Comment by goranche** [comment]
@mojcas you might also try the following... I'd try it out, but don't have a Windows machine available

    git update-index --chmod=+x manage.py

**Comment by mojcas** [comment]
Nice, thanks, it worked.

**Comment by goranche** [comment]
when trying out this PR, I get the following errors (tried `migrate`, `makemigrations` and `runserver`)

    <class 'api.admin.UserProfileAdmin'>: (admin.E108) The value of 'list_display[1]' refers to 'fullname', which is not a callable, an attribute of 'UserProfileAdmin', or an attribute or method on 'api.UserProfile'.
    <class 'api.admin.UserProfileAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'githubuser', which is not a callable, an attribute of 'UserProfileAdmin', or an attribute or method on 'api.UserProfile'.

**Comment by mojcas** [comment]
Please try again to makemigrations... Added fixed admin.py to match changed UserProfile mode

**Comment by gandalfar** [comment]
Closing this, as #174 already had same changes. @mojcas please correct me, if I got this wrong.

**Pull request closed without merging**
