### PR TITLE
Initialize current project on the new task form

### PR DESCRIPTION
**Pull request by livike**
Sets the default value of the project to current project (task is created from the project). You are still able to change the value from the dropdown.

### CODE REVIEW

**Comment by anuschka** [comment]
@livike when I click on the "Add new task" button inside the project form I get the message "Looks like you already signed in!". Since I am logged in it should not ask me to login again and I don't want to logout :wink:

**Comment by anuschka** [comment]
Sorry @livike my bad... User did not have permission to add tasks :angel:

**Comment by anuschka** [comment]
Even though user has all api permissions when I click on Tasks from the menu or from project using "Add new task" I get error "In template /TrackCat/web/templates/pages/tasks.html, error at line 14".

**Comment by livike** [comment]
What is the logged in users activity status value in User Profiles? It must be ActiveCat or MentorCat. This will set up all the permissions for the user.

**Comment by anuschka** [comment]
Activity status for signed in user in User Profile is Active Cat.

**Comment by livike** [comment]
Fixed.

**Pull request merged**
