### PR TITLE
Added Python social auth through Github 

### PR DESCRIPTION
**Pull request by anuschka**
Solved issue #118 . Added Python social auth through Github. You can login using the link on the Login/Profile page. The login link (Sign in to Github) will redirect you to the index (main) page. If you go back to the Login/Profile page it will show you are already signed in and will display your first and last name and give you the possibility to sign out. 

Make sure you follow README.md file to setup your settings_local.py file.

### CODE REVIEW

**Comment by goranche** [comment]
why (again) the "Issue 118" in the title? please make the title descriptive and reference the issue in the first comment

**Comment by goranche** [comment]
> Solved issue 118

@anuschka, references work if you add a pound sign in front of the number... like you did in the comment in the issue...

**Comment by ialja** [comment]
The PR includes basic settings for GitHub login (yay!), but the views don't reflect that yet. Right now, you only have the option to login, but no way of checking whether anything happened. Suggestion: look into displaying user info after user authenticates and adding a logout option.

**Comment by mojcas** [comment]
I was excited to see this GitHub Login (I merged in my #129  with PR from @anuschka ... sorry about that.. but why PRs are taking so long :crying_cat_face: ), but for some reason I get 404 error from GitHub.  What may I be doing wrong? I followed the instructions, redirect seems to work, but like something may be missing still? The URL I get when I click on "Sign in with GitHub" from TrackCat:
https://github.com/login/oauth/authorize?response_type=code&client_id=&redirect_uri=http%3A%2F%2F127.0.0.1%3A8000%2Fcomplete%2Fgithub%2F%3Fredirect_state%3DsB4eh99yAGZ2KPVyT9HYSKLMwjt5Iwpi&state=sB4eh99yAGZ2KPVyT9HYSKLMwjt5Iwpi
Does this work okay for you guys?

**Comment by goranche** [comment]
> I merged in my #129 with PR from @anuschka

what do you mean by this?

**Comment by mojcas** [comment]
I mean, I checked #128 and added code to my local branch, simply to try it out (but it seems to not work too well for me, as I described).. I will rollback locally, and just did the #129 again, to be clean.. It is taking long for PR to be merged? We want to see the updates. :smirk_cat:

**Comment by goranche** [comment]
> Is it taking too long for PR to be merged?

I don't know, you tell me...
I think (well... I know, but let's go with "think") that we set a rule, that a PR needs to be reviewed by your peers... I'm not seeing that being done, unfortunately

**Comment by ialja** [comment]
Did you add GitHub key/secret in settings_local.py, as described in the README?

And we're not merging a PR until comments are addressed.

**Comment by goranche** [comment]
> And we're not merging a PR until comments are addressed.

also, there's ^ that ^  :smile:

**Comment by mojcas** [comment]
@ialja Yes, I added these following README, GitHub key/secret in settings_local.py .. I got these values after I registered TrackCatz in GitHub..

**Comment by mojcas** [comment]
this rule, that a PR needs to be reviewed by peers. How are we doing this exactly?

**Comment by goranche** [comment]
@mojcas what's unclear about it?

**Comment by ialja** [comment]
@mojcas Use the FB group to recruit reviewers :grin:

**Comment by mojcas** [comment]
Well, for one, how you know that it has not been reviewed yet? Then, how many people must review it before it's done? And, how exactly can we review it, is there a way to pull @anuschka code, to see what it does? I was usually going for the master and run some tests... review=reading,or testing.. ? :thought_balloon:

**Comment by goranche** [comment]
@mojcas take a look at our FB group...

https://www.facebook.com/groups/codecats/permalink/330079463849521/
https://www.facebook.com/groups/codecats/permalink/330618447128956/

**Comment by mojcas** [comment]
Useful, thanks @goranche

**Comment by anuschka** [comment]
I am on it :thought_balloon: 
> Suggestion: look into displaying user info after user authenticates and adding a logout option.

**Comment by livike** [comment]
Sorry for being late on commenting... After installing the requirements and all other stuff from the readme, Github Sign-in works nicely for me! Great job @anuschka :+1:

**Pull request merged**
