### PR TITLE
Update member page to add member detail page, and some basic userprofile update

### PR DESCRIPTION
**Pull request by mojcas**
This PR addresses issue #142 and #138 to update member page and add member detail page, with some basic updateprofile updates.

Introduced new fields from PR #173 
fixed references to old UserProfile fields
introduce new forms/views around members

NOTES:
- When logging in with GitHub, a new User object is created, which is needed as a base object to create UserProfile
- Use Django site admin to add User's First Name/Last Name manually, and  to add new userprofiles
- Keep in mind this is first attempt to add this basic functionality, so it's still fragile (i.e. not much testing done yet)
- Need to add functionality for member to update own userprofile, not others

Please check, comment and I will fix it

### CODE REVIEW

**Comment by goranche** [comment]
this PR includes everything from #173 as well, which means that if we decide not to merge that one, this one is pretty much unmergeable too...

**Comment by mojcas** [comment]
@goranche that is clear. these go together.
I'm not sure why you would decide not to merge #173 though. 
:thought_balloon:

**Comment by goranche** [comment]
> these go together

riiiight :smile: how about no? (read the last paragraph)

> not sure why you would decide not to merge

hit shappens :wink:   I'm not saying we will or we should, but in general, it might happen

if this was a PR on [another project](https://github.com/debian-pi/raspbian-ua-netinst) where I call (some of) the shots, I'd reject this kind of PR in a heartbeat...

you should always group changes that belong together into one PR, that doesn't depend on another (for example, I'm pretty sure the migration from this PR belongs in the other one, the changes to the model and permissions are repeated from the other one, shouldn't be here, ...)

**Comment by goranche** [comment]
a.k.a. **never** assume two PRs will be merged, so it's ok to say "these go together"

**Comment by mojcas** [comment]
I hear you, but I've split this based on comments from @gandalfar in https://github.com/CodeCatz/TrackCat/pull/167
"You can make a sequence of three PR's, in this order:
   change the database model and going from MC to MENTOR, which other parts of code might reference
    introduce new fields and fix references to old fields
    introduce new forms/views around members"
What do you suggest me to do now about this?

**Comment by goranche** [comment]
our understanding of what's written seems to differ; I'd suggest waiting for @gandalfar and let him clarify... :wink:

**Comment by mojcas** [comment]
Please @goranche no more waiting.. This functionality is long overdue. Can you please check, comment and I will fix anything.

**Comment by goranche** [comment]
You've obviously talked about this with @gandalfar, and as I'm not aware of what was discussed, I stand by my suggestion

**Comment by mojcas** [comment]
Should I close these 2 PRs and do one more PR then, with all these changes together?

**Comment by goranche** [comment]
nope, do not combine the two PRs

**Comment by mojcas** [comment]
What then? :confused:

**Comment by gandalfar** [comment]
Great work @mojcas :+1:

**Comment by mojcas** [comment]
Thanks @gandalfar :smile_cat:

**Pull request merged**
