### PR TITLE
Admin interface for UserProfile Projects Tasks Events

### PR DESCRIPTION
**Pull request by anuschka**
Addressing #145.

### CODE REVIEW

**Comment by goranche** [comment]
this is a "duplicate" PR of #181, just in case we ever need to see the discussion about the changes again...
@anuschka please stop doing this "close and reopen new PR" stunt...

**Comment by anuschka** [comment]
The reason why I did it @goranche was the amount of files that got added to the PR #181 after I synched. I thought it was better to have only files related to this PR in it but correct me please.

**Comment by goranche** [comment]
@anuschka do I really need to repeat myself? :smile:

as far as I can tell now (which means I had to spend/waste additional time checking), there is no difference between #181 and this one... except for the following:

* we lost the discussion about the PR (ok, I commented on that and provided a link... but that's not the same thing)
* there is only one commit in this PR instead of 6 in the other... the final result is the same, which means...
* we (actually mostly you) lost the chain of changes that lead to this state

sure, maybe none of that will ever matter, maybe no one will ever care or look... but by that logic we can just stop using git altogether...

closing a PR and reopening it in it's final stage should be a last ditch attempt... well, second to last, the last is delete your repository and fork it again...

**Comment by anuschka** [comment]
OK my apologize :angel:

**Comment by goranche** [comment]
@anuschka please fix #181, so we can merge that one... except for the merge issues, that one is basically the same as this one

**Pull request closed without merging**
