### PR TITLE
Update member page to add member detail page,  and some basic userprofile update

### PR DESCRIPTION
**Pull request by mojcas**
This PR addresses issue #142 and #138 to update member page and add member detail page, with some basic updateprofile updates.

NOTE:
- When logging in with GitHub, a new User object is created, but still need Django site admin to add User's First Name/Last Name manually
- Use Django site admin for now to add new userprofiles
- Keep in mind this is first attempt to add this basic functionality, so it's still fragile (i.e. not much testing for exceptions, or checks yet)
- Pictures are uploaded to MEDIA\profile_picture directory (merged with @anuschka  PR #159)
- Need to add functionality for member to update own userprofile, not others

@ercchy :
Hope this can be merged quickly, so we can add this to the CodeCatz master, and then continue with the rest of the issues around members. I tried to keep it clean, maybe something unwanted sneaked in.
 Please check, comment and I will fix it.

### CODE REVIEW

**Comment by anuschka** [comment]
@mojcas Is there a reason why you did it on master?

**Comment by mojcas** [comment]
@anuschka my master got out of sync...

**Comment by ialja** [comment]
Why were several fields deleted from the UserProfile model?

**Comment by ialja** [comment]
Also, we've merge @anuschka PR, which also updated the Members page. Please sync your fork and include her changes into your PR (the migrations file will also be changed).

**Comment by mojcas** [comment]
@ialja some fields were removed from UserProfile model, because they are already in User Django model, such as first_name, last_name, active, etc. 
I merged with @anuschka PR now but for some reason profile picture does not updated on update profile page (need to use Django site admin).

**Comment by gandalfar** [comment]
@mojcas This PR doesn't work fully work. Quick check gives me fatal error for `user_new`. So I'm not sure how much it was tested.

I also feel like it's trying to do too many things:
- introduce new form/view
- change the database model and going from `MC` to `MENTOR`, which other parts of code might code
- introduce member pages

I suggest you go through this PR and copy each of the functionality into separate PR that does just one of the above things. It will make merging and testing this much easier.

**Comment by mojcas** [comment]
@gandalfar can you tell me more, what user_new? It was tested in a way, that you need to run these steps, after completing migrations:
1) login with github > find in Django admin that a user was created
2) create a new userprofile in Django admin
3) from here, you can see members (userprofiles actually), see member detail page, and edit the user profile (to set picture, and some user details)
Please try.. and if really I must, then I will break it into separate PRs... but if it goes into master alltogether, then we get a nice chunk to continue working on this functionality..

**Comment by gandalfar** [comment]
How did you test this url:
`url(r'^member/new/$', views.user_new, name='member-new')`

**Comment by gandalfar** [comment]
It's not really that tied together. You can make a sequence of three PR's, in this order:

- change the database model and going from MC to MENTOR, which other parts of code might reference
- introduce new fields and fix references to old fields
- introduce new forms/views around members

You can also keep this PR, but because of amount of different changes it introduces (migrations, new outputs, new forms), it's going to take much more effort to test.

**Comment by mojcas** [comment]
This member/new/ is not working yet -- see NOTE above 
(...Use Django site admin for now to add new userprofiles...)

**Comment by gandalfar** [comment]
If it's not working, then it doesn't belong into PR. Unless it's a trap so that someone else can lose time later debugging it (since note in this PR is the only indication that it doesn't work) ;)

**Comment by mojcas** [comment]
it is not linked from the page, but if we can quickly remove this URL, what then?

**Comment by gandalfar** [comment]
Then you have a few other issues.

- incorrectly closed html <li> in members page
- you've changed permissions of manage.py, breaking ./ (and some other files - https://www.dropbox.com/s/60z9uj38l0pgfs3/Screenshot%202015-02-21%2021.23.25.png?dl=0 )
-* you have commented out HTML in commit
-* you still have dead code in this PR - whole `user_new` function

Because of changes to models, it also breaks other merge of admin.py, but that's an easy fix, just remove old fields from admin.

I've suggested breaking this PR into smaller ones, so I could give you better feedback on each functionality instead of discussing unconnected modules. But i'm fine also not doing that.

To get this merged in, fix the issues with -* . So I can test only parts that are working and for rest create a new PR.

**Comment by mojcas** [comment]
Ok, will do systematically tomorrow. Thanks for your comments.

**Pull request closed without merging**
