### PR TITLE
Fixed render for index.html in views.py

### PR DESCRIPTION
**Pull request by anuschka**
Addressed @gandalfar comment in #186.

### CODE REVIEW

**Comment by gandalfar** [comment]
Next time, make a new branch.

**Comment by anuschka** [comment]
It was branch "render" :confused:

**Comment by gandalfar** [comment]
Sorry :( My bad. I read `master`. Rule for me, don't merge before having morning coffee.

**Comment by anuschka** [comment]
Thanks. No worries :coffee: rules :+1:

**Pull request merged**
