### PR TITLE
Removed privacy page from templates

### PR DESCRIPTION
**Pull request by anuschka**
Addressed #180.

### CODE REVIEW

**Comment by mojcas** [comment]
@anuschka removing privacy page? Why? We don't like it?

**Comment by anuschka** [comment]
Well, I thought we do not have a link to it in the footer and therefore we can get rid of the file.

**Comment by mojcas** [comment]
You sure? I though I have seen the link somewhere :)

**Comment by ialja** [comment]
@mojcas It is very easy to check whether the link is there or not.

@anuschka If you're removing a page, make sure you also remove other things associated with that page (urls, views ...) or else you'll quickly end up with messy code full of leftover.

**Pull request merged**
