### PR TITLE
Added deadline countdown timer, counting down the days...

### PR DESCRIPTION
**Pull request by goranche**

### CODE REVIEW

**Comment by anuschka** [comment]
It works like a time :bomb: on all the pages :+1:

**Comment by goranche** [comment]
:smiling_imp:

**Comment by NinaNinchy** [comment]
Isn't the timer set 2 hours ahead of real time?

**Comment by goranche** [comment]
No

**Comment by NinaNinchy** [comment]
ok then. Works good overall.

**Pull request merged**
