### PR TITLE
Modified members page to be dynamic

### PR DESCRIPTION
**Pull request by mojcas**
Removed static contents from members page and replaced with calls to members model data

### CODE REVIEW

**Comment by goranche** [comment]
the problem with this pull request is that it includes all the commits from #127 as well, because you have been working on this on your master branch...

I'm sorry, but this PR will almost certainly be closed...

**Comment by goranche** [comment]
the reason why this happened is because you created your dynamic_member branch after you already commited the changes needed for the other PR, causing them to be included in this one

**Comment by mojcas** [comment]
@goranche no problem, but what should I do next then?

**Comment by mojcas** [comment]
I'll close this then.

**Comment by goranche** [comment]
@mojcas  I'm afraid there isn't much you can do, because you've created the #127 from master...
you could recreate your branch from a commit prior to any commits in the #127 PR, I guess, but I'm not sure that's something I'd recommend, as it required quite a bit of knowledge about git

if you want, take a look at "git log" and after that, try to find (google) how to create a branch from a specific commit

**Comment by mojcas** [comment]
It's okay..I only did a few small changes. Will do another PR... I guess? :thought_balloon:

**Comment by goranche** [comment]
but make sure to create a branch that doesn't include the commits from the other PR

**Comment by mojcas** [comment]
Yes, I will roll back.. :smile_cat:

**Pull request closed without merging**
